# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Heath Stewart's Blog
author: Heath Stewart
email: heaths@heaths.dev
tagline: Technical help and personal events
description: >-
  Technical posts about my decades-long experience with installation, current news
  and information about my current role in Azure, and tips and tricks I've
  picked up along the way. Occasionally about my backpacking and mountaineering
  adventures with friends and family.
show_excerpts: true
baseurl: "" # the subpath of your site, e.g. /blog
url: https://heaths.dev

minima:
  social_links:
    github: heaths
    keybase: heaths
    linkedin: heaths
    twitter: mrhestew
    instagram: mrhestew

twitter:
  username: mrhestew
  card: summary

social:
  name: Heath Stewart
  links:
  - https://github.com/heaths
  - https://keybase.io/heaths
  - https://linkedin.com/heaths
  - https://twitter.com/mrhestew
  - https://instagram.com/mrhestew

google_analytics: UA-151993669-1
webmaster_verifications:
  google: UA-151993669-1
  bing: DABE2342040BC3F3EDFC08253262FA39

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

# Test settings
port: 8080

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
