# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Heath Stewart's Blog
author: Heath Stewart
email: heaths@heaths.dev
tagline: Technical help and personal events
description: >-
  Technical posts about my decades-long experience with installation, current news
  and information about my current role in Azure, and tips and tricks I've
  picked up along the way. Occasionally about my backpacking and mountaineering
  adventures with friends and family.
show_excerpts: true
excerpt_separator: <!--more-->
baseurl: "" # the subpath of your site, e.g. /blog
url: https://heaths.dev

# Build settings
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-redirect-from
- jekyll-relative-links
- jekyll-seo-tag
- jekyll-sitemap

# Test settings
port: 4000

# Collections
collections:
  archive:
    output: true
header_pages:
- archive.md
- about.md

# Content settings
defaults:
- scope:
    path: ''
    type: posts
  values:
    author: Heath Stewart
    layout: post
- scope:
    path: ''
    type: archive
  values:
    layout: article
    permalink: /archive/:categories/:title:output_ext

relative_links:
  collections: true

minima:
  social_links:
    github: heaths
    bluesky: heaths.dev
    mastodon:
    - username: heaths
      instance: fosstodon.org
    linkedin: heaths
    instagram: mrhestew
    keybase: heaths

twitter:
  username: mrhestew
  card: summary

google_analytics: UA-151993669-1
webmaster_verifications:
  google: UA-151993669-1
  bing: DABE2342040BC3F3EDFC08253262FA39

exclude:
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE.txt
- README.md
